---
title: "Reproducible Research Project 2"
author: "ehagan"
date: "Saturday, May 23, 2015"
output: 
  html_document:
    keep_md: true
---

```{r workingDir,echo=FALSE}
# Working from GitHub directory
setwd("D:/GitHub/datasciencecoursera/RepData_PeerAssessment2/")
```

Download the NOAA storm database.
```{r loadData}
dataUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
fileName = "StormData.csv.bz2"

if (! file.exists(fileName)) {
    # Download and check return code. 0 is success, non-zero is error. May also throw exception.
    if (0 != download.file(url=dataUrl, destfile=fileName)) {
        stop("Failed to download data file: " + dataUrl)
    }
}
```

Compute database checksum and verify it matches the known checksum.
```{r}
library(tools)
checkSum <- md5sum(fileName)
if (checkSum != "df4aa61fff89427db6b7f7b1113b5553") {
    stop("Data md5sum does not match known value")
}
```

Load database if it is not already cached.
```{r}
# Read csv can automatically handle compressed csv files.
if(!exists("weatherData") | (nrow(weatherData) != 902297) | (ncol(weatherData) != 37))  {
    weatherData <- as.data.frame(read.csv(fileName))
}
```

Compute summary statistics for fatalities and injuries by event type.
```{r cache=TRUE}
fatalitySum  <- aggregate(FATALITIES ~ EVTYPE, data=weatherData, sum)
fatalityMean <- aggregate(FATALITIES ~ EVTYPE, data=weatherData, mean)
injurySum    <- aggregate(INJURIES ~ EVTYPE, data=weatherData, sum)
injuryMean   <- aggregate(INJURIES ~ EVTYPE, data=weatherData, mean)
```

Sort the summary data so that the most damaging events are first and create plots.
```{r}
```
